relative/relative/urls.py
from django.contrib import admin
from django.urls import path,include
from relativeap import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name= 'index'),
    path('relativeap/',include('relativeap.urls')),
    path('logout/',views.user_logout, name='logout')
]

relative/relativeap/urls.py
from django.urls import path
from relativeap import views

app_name = 'relativeap'

urlpatterns=[
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
    path('register/',views.register, name='register'),
    path('user_login/',views.user_login,name='user_login')
]

relative/relativeap/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

relative/relativeap/forms.py
from django import forms
from django.contrib.auth.models import User
from relativeap.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

relative/relativeap/views.py
from django.shortcuts import render
from relativeap.forms import UserForm, UserProfileForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    mydict = {"text":"HI prakash", "number":20}
    return render(request, 'relativeap/index.html',context=mydict)

def other(request):
    return render(request, 'relativeap/other.html')

def relative(request):
    return render(request, 'relativeap/relative_url_template.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'relativeap/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered
                   })

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account is not active")
        else:
            print("someone tried to login it is failed")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse('invalid login details given')
    else:
        return render(request,'relativeap/login.html')

@login_required 
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

relative/templates/relativeap/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>BASE</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index'%}">Django home</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'relativeap:register'%}">Register</a></li>

                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout'%}">logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'relativeap:user_login'%}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}
        {% endblock %}

    </div>
</body>
</html>

relative/templates/relativeap/index.html
<!DOCTYPE html>
{% extends "relativeap/base.html"%}
{% block body_block%}
    <h1>Welcome to index page</h1>
    <h1>{{ text|cut:'HI' }}</h1>
    <h1>{{ number|add:"30" }}</h1>
{% endblock %}

relative/templates/relativeap/login.html
<!DOCTYPE html>
{% extends "relativeap/base.html"%}
{% block body_block %}

<div class="jumbotron">
    <h1>Please login here </h1>
    <form action="{% url 'relativeap:user_login' %}" method="post">
        {% csrf_token%}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter username">

        <label for="password">Password:</label>
        <input type="password" name="password" >

        <input type="submit" value="Login">

    </form>

</div>

{% endblock %}

relative/templates/relativeap/other.html
<!DOCTYPE html>
{% extends "relativeap/base.html"%}
{% block body_block%}
    <h1>Welcome to other page</h1>
    <h2>this is an example of inheritance</h2>
    {% endblock %}

relative/templates/relativeap/registration.html
{% extends 'relativeap/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registration</h1>
    {% else %}
    <h1>Regsiter Here!</h1>
    <form enctype="multipart/form-data"  method="post">
        {% csrf_token %}
        {{ user_form }}
        {{ profile_form }}
        <input type="submit" name="" value="register">
    </form>
    {% endif %}
</div>

{% endblock %}

relative/templates/relativeap/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>relative page</title>
</head>
<body>
    <h1>Welcome to relative page</h1>
    <a href="{% url 'relativeap:other' %}">link to other page </a>
    <a href="{% url 'admin:index' %}"> admin link</a>
</body>
</html>